### PR TITLE
Module2: DRY KISS YANGI

### PR DESCRIPTION
**Pull request by Shedrack-Sunday**
A comprehensive pull request to access the best practices of javascript with the following:

- [ ] DRY

- [ ] KISS

- [ ] YANGI

### CODE REVIEW

**Comment by JonahKayizzi** [comment]
### Nice work @Shedrack-Sunday 

- Your design looks perfect ✔️ 
- Like how you separated the object logic from the view logic ✔️ 
- App functionality is super✔️ 
- No linter errors ✔️ 
- Proffesional PR and README ✔️ 

### Optional suggestions.

Here are a few changes I suggest so that your project conforms to Javascript best practices.

**Comment by JonahKayizzi** [comment]
The following code can be changed into  single line 
https://github.com/Shedrack-Sunday/Todo_List_Best_Practices_review/blob/028222b0989c1156b44fac2c94871459347b4761/src/components/index.js#L16-L17

**Comment by JonahKayizzi** [comment]
I suggest the use of object restructuring to access object properties to avoid repetition
https://github.com/Shedrack-Sunday/Todo_List_Best_Practices_review/blob/028222b0989c1156b44fac2c94871459347b4761/src/components/index.js#L17
https://github.com/Shedrack-Sunday/Todo_List_Best_Practices_review/blob/028222b0989c1156b44fac2c94871459347b4761/src/components/index.js#L104
https://github.com/Shedrack-Sunday/Todo_List_Best_Practices_review/blob/028222b0989c1156b44fac2c94871459347b4761/src/components/index.js#L108
https://github.com/Shedrack-Sunday/Todo_List_Best_Practices_review/blob/028222b0989c1156b44fac2c94871459347b4761/src/index.js#L19-L21

**Comment by JonahKayizzi** [comment]
I suggest that you consider creating a function for creating an HTML element and assigning IDs and classes to reduce the code repetitions in the `displayTasks = () => {` methods
https://github.com/Shedrack-Sunday/Todo_List_Best_Practices_review/blob/028222b0989c1156b44fac2c94871459347b4761/src/components/index.js#L43-L44

**Comment by Shedrack-Sunday** [comment]
> I suggest that you consider creating a function for creating an HTML element and assigning IDs and classes to reduce the code repetitions in the `displayTasks = () => {` methods
> 
> https://github.com/Shedrack-Sunday/Todo_List_Best_Practices_review/blob/028222b0989c1156b44fac2c94871459347b4761/src/components/index.js#L43-L44

**Comment by Shedrack-Sunday** [comment]
> I suggest the use of object restructuring to access object properties to avoid repetition
> 
> https://github.com/Shedrack-Sunday/Todo_List_Best_Practices_review/blob/028222b0989c1156b44fac2c94871459347b4761/src/components/index.js#L17
> 
> 
> https://github.com/Shedrack-Sunday/Todo_List_Best_Practices_review/blob/028222b0989c1156b44fac2c94871459347b4761/src/components/index.js#L104
> 
> 
> https://github.com/Shedrack-Sunday/Todo_List_Best_Practices_review/blob/028222b0989c1156b44fac2c94871459347b4761/src/components/index.js#L108
> 
> 
> https://github.com/Shedrack-Sunday/Todo_List_Best_Practices_review/blob/028222b0989c1156b44fac2c94871459347b4761/src/index.js#L19-L21

Thanks for the note. Do note that:

1. The restructuring of the code will alter the logic, as it's inside a function and not declared as an array due to the creation of the new elements. 
2. The Html is created inside of a function already, and creating another inside of it will cause a slow load time. I think this implementation is understandable because it's a block.

**Comment by Shedrack-Sunday** [comment]
> The following code can be changed into a single line
> 
> https://github.com/Shedrack-Sunday/Todo_List_Best_Practices_review/blob/028222b0989c1156b44fac2c94871459347b4761/src/components/index.js#L16-L17

Thanks for pointing it out. I'll work on this 👍

**Review by JonahKayizzi — APPROVED** [review]
### Status approved 🟢 

Changes have been well implemented. You can go ahead and merge your project

**Pull request merged**
